# Generated by Django 4.2.7 on 2025-08-31 19:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('rating', 'Rating'), ('comment', 'Comment')], max_length=20)),
                ('rating', models.IntegerField(blank=True, help_text='Rating from 1-5', null=True)),
                ('comment', models.TextField(blank=True, help_text="User's feedback comment")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.conversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.message')),
            ],
            options={
                'verbose_name_plural': 'User feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
