# Generated by Django 4.2.7 on 2025-08-31 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF Document'), ('confluence', 'Confluence'), ('jira', 'Jira'), ('sharepoint', 'SharePoint')], max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('total_chunks', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('embedding_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('token_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chat.datasource')),
            ],
            options={
                'ordering': ['data_source', 'chunk_index'],
                'unique_together': {('data_source', 'chunk_index')},
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='use_company_data',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RAGQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retrieval_time', models.FloatField(blank=True, null=True)),
                ('generation_time', models.FloatField(blank=True, null=True)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_queries', to='chat.conversation')),
                ('retrieved_chunks', models.ManyToManyField(related_name='queries', to='chat.documentchunk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
