# Generated by Django 4.2.7 on 2025-09-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_datasource_documentchunk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='use_company_data',
            field=models.CharField(choices=[('use', 'Use'), ('both', 'Both'), ('not_use', 'Not Use')], default='not_use', max_length=10),
        ),
    ]
